//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamScreenshotImporter.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal text() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamScreenshotImporter.Localization.text", typeof(text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 add folder 的本地化字符串。
        /// </summary>
        internal static string addfolder {
            get {
                return ResourceManager.GetString("addfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 add images 的本地化字符串。
        /// </summary>
        internal static string addimage {
            get {
                return ResourceManager.GetString("addimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag images here or 的本地化字符串。
        /// </summary>
        internal static string dragmsg {
            get {
                return ResourceManager.GetString("dragmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong path, select steam folder again! 的本地化字符串。
        /// </summary>
        internal static string errsteamdir {
            get {
                return ResourceManager.GetString("errsteamdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetching AppList... 的本地化字符串。
        /// </summary>
        internal static string getapplist {
            get {
                return ResourceManager.GetString("getapplist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting local apps... 的本地化字符串。
        /// </summary>
        internal static string getlocalmsg {
            get {
                return ResourceManager.GetString("getlocalmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting users... 的本地化字符串。
        /// </summary>
        internal static string getusermsg {
            get {
                return ResourceManager.GetString("getusermsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github 的本地化字符串。
        /// </summary>
        internal static string github {
            get {
                return ResourceManager.GetString("github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import finished. 的本地化字符串。
        /// </summary>
        internal static string imported {
            get {
                return ResourceManager.GetString("imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing to import. 的本地化字符串。
        /// </summary>
        internal static string noimage {
            get {
                return ResourceManager.GetString("noimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find path, select steam folder. 的本地化字符串。
        /// </summary>
        internal static string nosteamdir {
            get {
                return ResourceManager.GetString("nosteamdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile 的本地化字符串。
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing screenshot data... 的本地化字符串。
        /// </summary>
        internal static string savevdf {
            get {
                return ResourceManager.GetString("savevdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan Steam 的本地化字符串。
        /// </summary>
        internal static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total: {0} user(s), {1} app(s). 的本地化字符串。
        /// </summary>
        internal static string scantotal {
            get {
                return ResourceManager.GetString("scantotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App 的本地化字符串。
        /// </summary>
        internal static string selectapp {
            get {
                return ResourceManager.GetString("selectapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string selectuser {
            get {
                return ResourceManager.GetString("selectuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show all apps 的本地化字符串。
        /// </summary>
        internal static string showall {
            get {
                return ResourceManager.GetString("showall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong user or app! 的本地化字符串。
        /// </summary>
        internal static string wrongselect {
            get {
                return ResourceManager.GetString("wrongselect", resourceCulture);
            }
        }
    }
}
